### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by hey-aw** [hey-aw/teachers-assistant-ui#32]
The failure occurred because the command `pnpm` was not found. To resolve this issue, you need to ensure that `pnpm` is installed before running the `pnpm install` command. 

You can update your GitHub Actions workflow file to include a step to install `pnpm` before the install step. Here is the updated workflow configuration:

```yaml
name: Trigger auto deployment for teachers-eddo-ai

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    # Add other steps as needed
```

Add the `Install pnpm` step to ensure that `pnpm` is available for the subsequent steps.
